imports:
    - { resource: converters/output.yml } # services tagged by ezpublish.ezrichtext.converter.output.xhtml
    - { resource: converters/input.yml }  # services tagged by ezpublish.ezrichtext.converter.input.xhtml

parameters:
    ezrichtext.tag.namespace: fieldtypes.ezrichtext.tags
    ezrichtext.style.namespace: fieldtypes.ezrichtext.styles
    ezrichtext.embed.namespace: fieldtypes.ezrichtext.embed
    ezrichtext.resources: '%kernel.root_dir%/../vendor/ezsystems/ezplatform-richtext/src/lib/eZ/RichText/Resources'

    ezrichtext.converter.input.xhtml5.resources: '%ezrichtext.resources%/stylesheets/xhtml5/edit/docbook.xsl'
    ezrichtext.converter.edit.xhtml5.resources: '%ezrichtext.resources%/stylesheets/docbook/xhtml5/edit/xhtml5.xsl'

    ezrichtext.validator.docbook.resources:
        - '%ezrichtext.resources%/schemas/docbook/ezpublish.rng'
        - '%ezrichtext.resources%/schemas/docbook/docbook.iso.sch.xsl'
    ezrichtext.validator.output.ezxhtml5.resources:
        - '%ezrichtext.resources%/schemas/ezxhtml5/output/ezxhtml5.xsd'

services:
    ezrichtext.normalizer.input:
        class: EzSystems\EzPlatformRichText\eZ\RichText\Normalizer\DocumentTypeDefinition
        arguments:
            - 'section'
            - 'http://ez.no/namespaces/ezpublish5/xhtml5/edit'
            - '%ezrichtext.resources%/dtd/ezxhtml5_edit_html_character_entities.dtd'

    ezrichtext.converter.input.dispatcher:
        class: EzSystems\EzPlatformRichText\eZ\RichText\ConverterDispatcher
        arguments:
            -
                http://docbook.org/ns/docbook: null
                http://ez.no/namespaces/ezpublish5/xhtml5/edit: '@ezrichtext.converter.input.xhtml5'

    ezrichtext.renderer:
        class: EzSystems\EzPlatformRichTextBundle\eZ\RichText\Renderer
        arguments:
            - '@ezpublish.api.repository'
            - '@security.authorization_checker'
            - '@ezpublish.config.resolver'
            - '@templating'
            - '%ezrichtext.tag.namespace%'
            - '%ezrichtext.style.namespace'
            - '%ezrichtext.embed.namespace%'
            - '@?logger'
            - '%ezplatform.ezrichtext.custom_tags%'
            - '%ezplatform.ezrichtext.custom_styles%'

    ezrichtext.validator.input.ezxhtml5:
        class: EzSystems\EzPlatformRichText\eZ\RichText\Validator\ValidatorAggregate
        arguments: [!tagged ezrichtext.validator.input.ezxhtml5]

    ezrichtext.validator.docbook:
        class: EzSystems\EzPlatformRichText\eZ\RichText\Validator\Validator
        arguments: ['%ezrichtext.validator.docbook.resources%']
        tags:
            - { name: 'ezrichtext.validator.input.ezxhtml5' }

    ezrichtext.validator.output.ezxhtml5:
        class: EzSystems\EzPlatformRichText\eZ\RichText\Validator\Validator
        arguments: ['%ezrichtext.validator.output.ezxhtml5.resources%']

    ezrichtext.validator.input.dispatcher:
        class: EzSystems\EzPlatformRichText\eZ\RichText\Validator\ValidatorDispatcher
        arguments:
            -
                http://docbook.org/ns/docbook: null
                http://ez.no/namespaces/ezpublish5/xhtml5/edit: null
                http://ez.no/namespaces/ezpublish5/xhtml5: '@ezrichtext.validator.output.ezxhtml5'

    ezrichtext.validator.internal_link:
        class: EzSystems\EzPlatformRichText\eZ\RichText\Validator\InternalLinkValidator
        arguments:
            - '@ezpublish.spi.persistence.cache.contentHandler'
            - '@ezpublish.spi.persistence.cache.locationHandler'
        tags:
            - { name: 'ezrichtext.validator.input.ezxhtml5' }

    ezrichtext.converter.edit.xhtml5:
        class: EzSystems\EzPlatformRichTextBundle\eZ\RichText\Converter\Html5Edit
        arguments:
            - '%ezrichtext.converter.edit.xhtml5.resources%'
            - '@ezpublish.config.resolver'
        lazy: true
