system:
    default:
        fieldtypes:
            ezrichtext:
                custom_tags: [ezyoutube, eztwitter]

ezrichtext:
    # Define Custom Tags
    custom_tags:
        ezyoutube:
            template: '@EzPlatformRichTextFieldType/custom_tag/ezyoutube.html.twig'
            icon: '/bundles/ezplatformrichtextfieldtype/custom_tag/icon/youtube-color.svg#youtube-color'
            attributes:
                title:
                    type: 'string'
                    required: true
                    default_value: ''
                video_url:
                    type: 'string'
                    required: true
                width:
                    type: 'number'
                    required: true
                    default_value: 640
                height:
                    type: 'number'
                    required: true
                    default_value: 360
                autoplay:
                    type: 'boolean'
                    default_value: false
                align:
                    type: 'choice'
                    required: false
                    default_value: 'left'
                    choices: ['left', 'center', 'right']

        eztwitter:
            template: '@EzPlatformRichTextFieldType/custom_tag/eztwitter.html.twig'
            icon: '/bundles/ezplatformrichtextfieldtype/custom_tag/icon/twitter.svg#twitter'
            attributes:
                tweet_url:
                    type: 'string'
                    required: true
                # see https://dev.twitter.com/web/embedded-tweets/parameters
                cards:
                    type: 'choice'
                    required: false
                    default_value: ''
                    choices: ['', 'hidden']
                conversation:
                    type: 'choice'
                    default_value: ''
                    choices: ['', 'none']
                theme:
                    type: 'choice'
                    default_value: 'light'
                    required: true
                    choices: ['light', 'dark']
                link_color:
                    type: 'string'
                    default_value: ''
                width:
                    type: 'number'
                    default_value: 250
                align:
                    type: 'choice'
                    default_value: 'left'
                    choices: [ 'left', 'right', 'center' ]
                lang:
                    type: 'string'
                    default_value: 'en'
                dnt:
                    type: 'boolean'
                    default_value: true
